# Generated by Django 6.0.5 on 2026-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_car_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='red'),
            preserve_default=False,
        ),
    ]
